title: Sreejith Rajeevan
# logo
description: A Data person diving deep into AWS services, Databricks, Pyspark, SQL. I'm all about optimizing data workflows and building scalable solutions.
show_downloads: true
theme: jekyll-theme-minimal 
